# Generated by Django 5.0.7 on 2026-09-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qasida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('lyrics', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_lyrics', models.TextField(blank=True)),
                ('suggested_tags', models.CharField(blank=True, help_text='Comma-separated suggested tags', max_length=200)),
                ('email', models.EmailField(help_text='Email for contact regarding this suggestion', max_length=254)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qasida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.qasida')),
            ],
        ),
        migrations.AddField(
            model_name='qasida',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='qasidas', to='core.tag'),
        ),
    ]
