# Generated by Django 5.0.7 on 2026-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parser_type', models.CharField(choices=[('mynaatbook', 'My Naat Book (React JS)'), ('desertechoblog', 'Desert Echo Blog (WordPress)'), ('damas', 'Damas Nur (WordPress)')], default='mynaatbook', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
