# Generated by Django 5.0.7 on 2026-09-02 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_initial_websites'),
    ]

    operations = [
        migrations.CreateModel(
            name='QasidaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qasida_scans/')),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qasida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.qasida')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='qasidaimage',
            constraint=models.UniqueConstraint(fields=('qasida', 'source_url'), name='unique_qasida_image_source'),
        ),
    ]
