# Generated by Django 5.0.7 on 2026-09-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_qasidaimage_qasidaimage_unique_qasida_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasida',
            name='text_quality',
            field=models.CharField(choices=[('ok', 'Extracted text'), ('ocr', 'OCR transcription'), ('poor', 'Unreliable - read the scans')], default='ok', max_length=8),
        ),
    ]
