# Generated by Django 5.0.7 on 2026-09-02 11:17

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_qasida_text_quality'),
    ]

    operations = [
        # gin_trgm_ops below comes from this extension.
        TrigramExtension(),
        migrations.AddField(
            model_name='qasida',
            name='arabic_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='qasida',
            name='search_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddIndex(
            model_name='qasida',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='qasida_search_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
