# Generated by Django 5.0.7 on 2026-09-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_qasida_arabic_title_qasida_search_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qasida',
            name='text_quality',
            field=models.CharField(choices=[('ok', 'Extracted text'), ('ocr', 'Reconstructed text'), ('poor', 'Unreliable - read the scans')], default='ok', max_length=8),
        ),
    ]
