# Generated by Django 5.0.7 on 2026-09-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_qasida_text_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasida',
            name='source_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qasidas', to='core.sourcewebsite'),
        ),
    ]
