# Generated by Django 5.0.7 on 2026-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_qasida_source_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasida',
            name='transliteration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sourcewebsite',
            name='parser_type',
            field=models.CharField(choices=[('mynaatbook', 'My Naat Book (React JS)'), ('desertechoblog', 'Desert Echo Blog (WordPress)'), ('damas', 'Damas Nur (WordPress)'), ('midhah', 'Midhah lyrics (Next.js, JSON-LD)')], default='mynaatbook', max_length=50),
        ),
    ]
