# Generated by Django 5.0.7 on 2026-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_qasida_transliteration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewebsite',
            name='parser_type',
            field=models.CharField(choices=[('mynaatbook', 'My Naat Book (React JS)'), ('desertechoblog', 'Desert Echo Blog (WordPress)'), ('damas', 'Damas Nur (WordPress)'), ('midhah', 'Midhah lyrics (Next.js, JSON-LD)'), ('generic', 'Generic (JSON-LD, else densest text block)')], default='mynaatbook', max_length=50),
        ),
    ]
