# Generated by Django 5.0.7 on 2026-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sourcewebsite_parser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasida',
            name='translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qasida',
            name='translation_origin',
            field=models.CharField(blank=True, choices=[('', 'No translation'), ('source', 'Published by the source'), ('machine', 'Machine translated')], default='', max_length=8),
        ),
    ]
