# Generated by Django 5.0.7 on 2026-09-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_qasida_translation_qasida_translation_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasida',
            name='review_state',
            field=models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved for display'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='qasida',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
