# Generated by Django 5.0.7 on 2026-09-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_qasida_review_state_qasida_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewebsite',
            name='parser_type',
            field=models.CharField(choices=[('mynaatbook', 'My Naat Book (React JS)'), ('desertechoblog', 'Desert Echo Blog (WordPress)'), ('damas', 'Damas Nur (WordPress)'), ('midhah', 'Midhah lyrics (Next.js, JSON-LD)'), ('generic', 'Generic (JSON-LD, else densest text block)'), ('wayback', 'Internet Archive snapshots of a blocked site')], default='mynaatbook', max_length=50),
        ),
        migrations.CreateModel(
            name='QasidaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Paste any YouTube link or the video id.', max_length=500)),
                ('video_id', models.CharField(blank=True, editable=False, max_length=32)),
                ('title', models.CharField(blank=True, help_text='Reciter or recording name, shown above the player.', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qasida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.qasida')),
            ],
            options={
                'verbose_name_plural': 'qasida media',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='qasidamedia',
            constraint=models.UniqueConstraint(fields=('qasida', 'video_id'), name='unique_qasida_video'),
        ),
    ]
