# Generated by Django 5.0.7 on 2026-09-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sourcewebsite_parser_type_qasidamedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('arabic_name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='qasida',
            name='collection_position',
            field=models.PositiveIntegerField(blank=True, help_text='Which part of the collection this is, counting from 1.', null=True),
        ),
        migrations.AddField(
            model_name='qasida',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='core.collection'),
        ),
    ]
