# Generated by Django 5.0.7 on 2026-09-05 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_qasida_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for contact regarding this suggestion', max_length=254),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='A private note, visible only to you.', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qasida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='core.qasida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_transliteration', models.BooleanField(default=True, help_text='Show the Latin script beside the original.')),
                ('show_translation', models.BooleanField(default=True, help_text='Show the translation beside the original.')),
                ('lyrics_size', models.CharField(choices=[('sm', 'Compact'), ('md', 'Comfortable'), ('lg', 'Large')], default='md', help_text='How large the verse itself is set.', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_count', models.PositiveIntegerField(default=1)),
                ('qasida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='core.qasida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reading history',
                'ordering': ('-last_read_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'qasida'), name='unique_favourite'),
        ),
        migrations.AddConstraint(
            model_name='readinghistory',
            constraint=models.UniqueConstraint(fields=('user', 'qasida'), name='unique_reading_history'),
        ),
    ]
