# Generated by Django 5.0.7 on 2026-09-06 14:02

from django.db import migrations, models


def file_existing_tags(apps, schema_editor):
    """
    Put every tag already in the database onto an axis.

    Runs the same rules the model uses, so a deployment sees no change in what
    the filters show - the grouping simply stops being recomputed from the
    name on every page view. Anything the rules do not recognise is left
    unfiled for an editor to place, rather than guessed into a group.
    """
    from core.models import Tag as TagModel

    Tag = apps.get_model('core', 'Tag')
    for tag in Tag.objects.all():
        tag.category = TagModel.classify(tag.name)
        tag.save(update_fields=['category'])


def unfile_tags(apps, schema_editor):
    """Reversing this only clears the column; no tag or relation is touched."""
    Tag = apps.get_model('core', 'Tag')
    Tag.objects.update(category='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_suggestion_user_alter_suggestion_email_favourite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('form', 'Form and theme'), ('language', 'Language'), ('maqam', 'Maqam (melodic mode)'), ('bahr', 'Bahr (metre)'), ('condition', 'Condition of the text'), ('other', 'Not yet filed')], db_index=True, help_text='Which axis this tag belongs to. Left blank, it is worked out from the name when the tag is saved.', max_length=12),
        ),
        migrations.RunPython(file_existing_tags, unfile_tags),
    ]
