# Generated by Django 5.0.7 on 2026-09-06 14:02

from django.db import migrations, models


# The filing rules, frozen as they stand here. A migration that imports the
# live model runs whatever the model says on the day it is applied - and
# breaks outright if the method is renamed - so a fresh install would no
# longer reproduce what this migration did. Later changes to Tag.classify
# belong in a migration of their own.
LANGUAGE_NAMES = frozenset({
    'arabic', 'urdu', 'english', 'spanish', 'turkish', 'swedish',
    'french', 'german', 'persian', 'farsi', 'punjabi', 'sindhi',
})
CONDITION_NAMES = frozenset({
    'transliterated', 'from-archive', 'lyrics-in-images', 'text-needs-review',
})
FORM_NAMES = frozenset({
    'naat', 'qasida', 'hamd', 'manqbat', 'manqabat', 'manzhuma',
    'durood-o-salam', 'sufiyana-kalam', 'mawlid-hadra', 'tawassul',
    'around-the-year', 'madih', 'nasheed', 'ghazal',
})
CATEGORY_PREFIXES = (('maqam-', 'maqam'), ('bahr-', 'bahr'), ('qasida-', 'form'))


def classify(name):
    key = (name or '').strip().lower()
    for prefix, category in CATEGORY_PREFIXES:
        if key.startswith(prefix):
            return category
    if key in LANGUAGE_NAMES:
        return 'language'
    if key in CONDITION_NAMES:
        return 'condition'
    if key in FORM_NAMES:
        return 'form'
    return 'other'


def file_existing_tags(apps, schema_editor):
    """
    Put every tag already in the database onto an axis.

    Runs the same rules the model uses, so a deployment sees no change in what
    the filters show - the grouping simply stops being recomputed from the
    name on every page view. Anything the rules do not recognise is left
    unfiled for an editor to place, rather than guessed into a group.
    """
    Tag = apps.get_model('core', 'Tag')
    for tag in Tag.objects.all():
        tag.category = classify(tag.name)
        tag.save(update_fields=['category'])


def unfile_tags(apps, schema_editor):
    """Reversing this only clears the column; no tag or relation is touched."""
    Tag = apps.get_model('core', 'Tag')
    Tag.objects.update(category='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_suggestion_user_alter_suggestion_email_favourite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('form', 'Form and theme'), ('language', 'Language'), ('maqam', 'Maqam (melodic mode)'), ('bahr', 'Bahr (metre)'), ('condition', 'Condition of the text'), ('other', 'Not yet filed')], db_index=True, help_text='Which axis this tag belongs to. Left blank, it is worked out from the name when the tag is saved.', max_length=12),
        ),
        migrations.RunPython(file_existing_tags, unfile_tags),
    ]
