# Generated by Django 5.0.7 on 2026-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='note',
            field=models.TextField(blank=True, help_text='What is wrong, and how you know'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_arabic_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_transliteration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='qasida',
            name='translation_origin',
            field=models.CharField(blank=True, choices=[('', 'No translation'), ('source', 'Published by the source'), ('machine', 'Machine translated'), ('reader', 'Corrected by a reader')], default='', max_length=8),
        ),
    ]
