# Generated by Django 5.0.7 on 2026-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_suggestion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasida',
            name='dedicated_to',
            field=models.CharField(blank=True, help_text='Who the qasida is addressed to or written in praise of.', max_length=200),
        ),
    ]
