# Generated by Django 5.2.17 on 2026-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_duplicate_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewebsite',
            name='parser_type',
            field=models.CharField(choices=[('mynaatbook', 'My Naat Book (React JS)'), ('desertechoblog', 'Desert Echo Blog (WordPress)'), ('damas', 'Damas Nur (WordPress)'), ('midhah', 'Midhah lyrics (Next.js, JSON-LD)'), ('generic', 'Generic (JSON-LD, else densest text block)'), ('wayback', 'Internet Archive snapshots of a blocked site'), ('wordpress_api', 'WordPress REST API (wp-json)')], default='mynaatbook', max_length=50),
        ),
    ]
