"""Let a work hold several hand-added scans, and several unrecognised links.

Relaxing only. Each unique constraint is replaced by the same constraint
limited to rows that have a key: a scan with a source URL, a recording with a
video id. Every row that satisfied the old constraint satisfies the new one,
so this cannot fail on existing data and changes none of it.
"""
# Generated by Django 5.2.17 on 2026-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_record_parser_choices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qasidaimage',
            name='unique_qasida_image_source',
        ),
        migrations.RemoveConstraint(
            model_name='qasidamedia',
            name='unique_qasida_video',
        ),
        migrations.AddConstraint(
            model_name='qasidaimage',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('qasida', 'source_url'), name='unique_qasida_image_source'),
        ),
        migrations.AddConstraint(
            model_name='qasidamedia',
            constraint=models.UniqueConstraint(condition=models.Q(('video_id', ''), _negated=True), fields=('qasida', 'video_id'), name='unique_qasida_video'),
        ),
    ]
