"""Record whether an account's address has been confirmed by its owner.

Additive. Two columns on the reader profile, both with defaults: every
existing profile is taken as confirmed, and no address changes. Only accounts
opened through the sign-up form from now on start unconfirmed.
"""
# Generated by Django 5.2.17 on 2026-09-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_allow_scans_and_videos_without_a_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerprofile',
            name='email_verified',
            field=models.BooleanField(default=True, help_text='The owner has confirmed the address is theirs.'),
        ),
        migrations.AddField(
            model_name='readerprofile',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='An address change waiting to be confirmed.', max_length=254),
        ),
    ]
