"""Record how an editor ruled a pair of works that read as duplicates.

Additive. Nullable or blank columns, empty on every existing row: the copy a
hidden work was replaced by, the copy kept in a ruled pair, and each copy's
review state before the ruling so that it can be undone exactly.
"""
# Generated by Django 5.2.17 on 2026-09-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_confirm_email_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatelink',
            name='hidden_was',
            field=models.CharField(blank=True, editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='duplicatelink',
            name='kept',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.qasida'),
        ),
        migrations.AddField(
            model_name='duplicatelink',
            name='kept_was',
            field=models.CharField(blank=True, editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='qasida',
            name='replaced_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='The copy kept in place of this one, when it was ruled a duplicate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='core.qasida'),
        ),
    ]
