"""Offer the crawler for sites printing each naat in several scripts.

Choices live only in Python; this changes nothing in the database.
"""
# Generated by Django 5.2.17 on 2026-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_record_duplicate_rulings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewebsite',
            name='parser_type',
            field=models.CharField(choices=[('mynaatbook', 'My Naat Book (React JS)'), ('desertechoblog', 'Desert Echo Blog (WordPress)'), ('damas', 'Damas Nur (WordPress)'), ('midhah', 'Midhah lyrics (Next.js, JSON-LD)'), ('generic', 'Generic (JSON-LD, else densest text block)'), ('wayback', 'Internet Archive snapshots of a blocked site'), ('wordpress_api', 'WordPress REST API (wp-json)'), ('multiscript', 'Roman, Hindi and Urdu on one page (WordPress or Blogger)')], default='mynaatbook', max_length=50),
        ),
    ]
