"""
Django settings for qasida_app project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse, urlunparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-default-key-do-not-use-in-prod")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Behind a TLS-terminating proxy (Traefik), the request reaches Django over
# plain HTTP. Without this Django builds http:// URLs and rejects form posts,
# because the browser's Origin says https while Django believes otherwise.
# Only trust the header when a proxy is actually in front, or a client could
# claim to be on HTTPS.
if os.environ.get("DJANGO_BEHIND_PROXY", "") == "True":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

# Django 4+ checks the Origin header against this list for unsafe methods, so
# the admin and the suggestion form need the site's own https origin here.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Cookies only over HTTPS once a proxy terminates TLS for us.
SESSION_COOKIE_SECURE = os.environ.get("DJANGO_SECURE_COOKIES", "") == "True"
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    'core',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

ROOT_URLCONF = "qasida_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-level templates win over app templates, which is what lets
        # templates/admin/base_site.html rebrand the admin.
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.library_stats",
            ],
        },
    },
]

WSGI_APPLICATION = "qasida_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'qasida_db'),
        'USER': os.environ.get('DB_USER', 'qasida_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'qasida_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

from celery.schedules import crontab

# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {
    'run-crawlers-every-midnight': {
        'task': 'core.tasks.run_crawlers',
        'schedule': crontab(minute=0, hour=0),
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Refuses a password built out of the username or email.
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    # Ten rather than Django's eight. Length is the single largest factor in
    # how hard a password is to guess, and it costs the person nothing to type.
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 10},
    },
    # Django ships a list of the 20,000 commonest passwords.
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    # One character class only - all letters, all digits - is what most weak
    # passwords that survive the list above look like.
    {
        "NAME": "core.validators.ComplexityValidator",
    },
]


# Authentication
#
# Readers sign in with a username or an email address, so the project backend
# is tried first; Django's own stays behind it, which keeps the admin and any
# management command working exactly as before.

AUTHENTICATION_BACKENDS = [
    "core.auth_backends.UsernameOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "my_library"
# No LOGOUT_REDIRECT_URL on purpose: signing out renders a page that
# confirms it happened, and that page is what empties the offline cache
# of anything rendered while signed in.

# A session cookie that outlives the browser is only kept when the person asks
# for it on the sign-in form; otherwise the login view shortens it to the
# session. Two weeks is Django's default and is the "remember me" duration.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True

# Failed sign-in attempts allowed before the form starts refusing, which stops
# it being used to walk a password list. Counted separately per account and per
# address: readers on one mosque or household connection share an address, so
# that limit is much looser - it is there to catch a machine grinding through
# accounts, not a family getting a password wrong. See core.account_views.
LOGIN_ATTEMPT_LIMIT = 8
LOGIN_ATTEMPT_LIMIT_PER_IP = 40
LOGIN_ATTEMPT_WINDOW = 15 * 60


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

# Scans downloaded by the crawlers. This lands inside the bind-mounted project
# directory, so the files survive container rebuilds without an extra volume.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Password reset is the only mail this site sends. The console backend is the
# default so a development container never tries to reach a mail server; set
# DJANGO_EMAIL_BACKEND to the SMTP backend in production and the reset link is
# delivered for real.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "no-reply@localhost")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# How long a password reset link stays usable.
PASSWORD_RESET_TIMEOUT = 60 * 60 * 3


# Cache
#
# Used for the sign-in attempt counters and nothing else, so it shares the
# Redis that Celery already needs, on a different database. Every read and
# write goes through a helper that swallows connection errors: if Redis is
# away the site keeps working, it simply stops counting.

def _cache_location():
    override = os.environ.get("DJANGO_CACHE_URL", "").strip()
    if override:
        return override
    parts = urlparse(CELERY_BROKER_URL)
    return urlunparse(parts._replace(path="/1"))


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": _cache_location(),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
